In [1]:
import numpy as np
import sklearn as skl
from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
import yaml
# yaml is a data format that's easy to read
import requests
from sklearn.model_selection import train_test_split

%matplotlib inline


In [2]:
# df = pd.read_csv('https://bit.ly/2T5SEKT')
df = pd.read_csv('https://bit.ly/2T5SEKT', header = None)

In [3]:
df.head()

0  1    2      3      4       5       6        7       8       9   ...  \
0  119513  N   31  18.02  27.60  117.50  1013.0  0.09489  0.1036  0.1086  ...   
1    8423  N   61  17.99  10.38  122.80  1001.0  0.11840  0.2776  0.3001  ...   
2  842517  N  116  21.37  17.44  137.50  1373.0  0.08836  0.1189  0.1255  ...   
3  843483  N  123  11.42  20.38   77.58   386.1  0.14250  0.2839  0.2414  ...   
4  843584  R   27  20.29  14.34  135.10  1297.0  0.10030  0.1328  0.1980  ...   

       25      26      27      28      29      30      31       32   33  34  
0  139.70  1436.0  0.1195  0.1926  0.3140  0.1170  0.2677  0.08113  5.0   5  
1  184.60  2019.0  0.1622  0.6656  0.7119  0.2654  0.4601  0.11890  3.0   2  
2  159.10  1949.0  0.1188  0.3449  0.3414  0.2032  0.4334  0.09067  2.5   0  
3   98.87   567.7  0.2098  0.8663  0.6869  0.2575  0.6638  0.17300  2.0   0  
4  152.20  1575.0  0.1374  0.2050  0.4000  0.1625  0.2364  0.07678  3.5   0  

[5 rows x 35 columns]

In [4]:
req = requests.get('https://bit.ly/2F5cnoS')

In [5]:
req.text

'- Mean Radius\n- Mean Texture\n- Mean Perimeter\n- Mean Area\n- Mean Smoothness\n- Mean Compactness\n- Mean Concavity\n- Mean ConcavetyCount\n- Mean Symmetry \n- Mean Fractal Dimension\n- Std Radius\n- Std Texture\n- Std Perimeter\n- Std Area\n- Std Smoothness\n- Std Compactness\n- Std Concavity\n- Std ConcavetyCount\n- Std Symmetry \n- Std Fractal Dimension\n- Worst Radius\n- Worst Texture\n- Worst Perimeter\n- Worst Area\n- Worst Smoothness\n- Worst Compactness\n- Worst Concavity\n- Worst ConcavetyCount\n- Worst Symmetry \n- Worst Fractal Dimension'

In [6]:
names = yaml.load(req.text)
names

['Mean Radius',
 'Mean Texture',
 'Mean Perimeter',
 'Mean Area',
 'Mean Smoothness',
 'Mean Compactness',
 'Mean Concavity',
 'Mean ConcavetyCount',
 'Mean Symmetry',
 'Mean Fractal Dimension',
 'Std Radius',
 'Std Texture',
 'Std Perimeter',
 'Std Area',
 'Std Smoothness',
 'Std Compactness',
 'Std Concavity',
 'Std ConcavetyCount',
 'Std Symmetry',
 'Std Fractal Dimension',
 'Worst Radius',
 'Worst Texture',
 'Worst Perimeter',
 'Worst Area',
 'Worst Smoothness',
 'Worst Compactness',
 'Worst Concavity',
 'Worst ConcavetyCount',
 'Worst Symmetry',
 'Worst Fractal Dimension']

In [7]:
names = ['id', 'target'] + names

In [8]:
len(names)

32

In [9]:
df.shape

(198, 35)

In [10]:
# all the rows, 3 one over to the end
X = df.iloc[:, 2:].values
y = df.iloc[:, 1].values

In [11]:
X.shape

(198, 33)

In [12]:
X[:10, :]

array([[31, 18.02, 27.6, 117.5, 1013.0, 0.09489, 0.1036, 0.1086, 0.07055,
        0.1865, 0.06333, 0.6249, 1.89, 3.972, 71.55,
        0.0044329999999999994, 0.014209999999999999,
        0.032330000000000005, 0.009854, 0.01694, 0.0034950000000000003,
        21.63, 37.08, 139.7, 1436.0, 0.1195, 0.1926, 0.314,
        0.11699999999999999, 0.2677, 0.08113, 5.0, '5'],
       [61, 17.99, 10.38, 122.8, 1001.0, 0.1184, 0.2776, 0.3001, 0.1471,
        0.2419, 0.07871, 1.095, 0.9053, 8.589, 153.4, 0.006399, 0.04904,
        0.05372999999999999, 0.01587, 0.03003, 0.006193, 25.38, 17.33,
        184.6, 2019.0, 0.1622, 0.6656, 0.7119, 0.2654, 0.4601, 0.1189,
        3.0, '2'],
       [116, 21.37, 17.44, 137.5, 1373.0, 0.08836000000000001, 0.1189,
        0.1255, 0.0818, 0.2333, 0.0601, 0.5854, 0.6105, 3.928, 82.15,
        0.006167, 0.03449, 0.033, 0.01805, 0.03094, 0.005039, 24.9,
        20.98, 159.1, 1949.0, 0.1188, 0.3449, 0.3414, 0.2032, 0.4334,
        0.09067, 2.5, '0'],
       [123, 11.4

In [13]:
y[:10]
# N - nonreoccur, R - reoccur

array(['N', 'N', 'N', 'N', 'R', 'R', 'N', 'R', 'N', 'N'], dtype=object)

In [14]:
y[:10]
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder


In [15]:
X = df.loc[:, 2:33].values
X.shape

(198, 32)

In [16]:
le = LabelEncoder()
y = le.fit_transform(df.loc[:, 1])
y[:10]

array([0, 0, 0, 0, 1, 1, 0, 1, 0, 0])

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size = 0.2,stratify = y,random_state = 42)

In [18]:
pipe_lr = make_pipeline(StandardScaler(), 
                        PCA(n_components = 10), 
                        LogisticRegression(random_state = 42))

In [19]:
pipe_lr.fit(X_train, y_train)

c:\users\shamp\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Pipeline(memory=None,
     steps=[('standardscaler', StandardScaler(copy=True, with_mean=True, with_std=True)), ('pca', PCA(copy=True, iterated_power='auto', n_components=10, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)), ('logisticregression', LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=42, solver='warn',
          tol=0.0001, verbose=0, warm_start=False))])

In [20]:
print("test accuracy: {}".format(pipe_lr.score(X_test, y_test)))

test accuracy: 0.725


In [21]:
y_pred = pipe_lr.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
from sklearn.model_selection import StratifiedKFold


In [23]:
kfold = StratifiedKFold(n_splits=10,random_state=42).split(X_train,y_train)

In [24]:
scores = []
for k,(train,test) in enumerate(kfold):
    pipe_lr .fit(X_train[train],y_train[train])
    score = pipe_lr.score(X_train[test],y_train[test])
    scores.append(score)
    print("Fold: {},class dist.:{},Acc: {}".format(k,np.bincount(y_train[train]),score))
    

Fold: 0,class dist.:[108  34],Acc: 0.75
Fold: 1,class dist.:[108  34],Acc: 0.8125
Fold: 2,class dist.:[108  34],Acc: 0.8125
Fold: 3,class dist.:[108  34],Acc: 0.8125
Fold: 4,class dist.:[108  34],Acc: 0.875
Fold: 5,class dist.:[108  34],Acc: 0.75
Fold: 6,class dist.:[108  34],Acc: 0.75
Fold: 7,class dist.:[108  34],Acc: 0.75
Fold: 8,class dist.:[108  35],Acc: 0.7333333333333333
Fold: 9,class dist.:[108  35],Acc: 0.8666666666666667


c:\users\shamp\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
c:\users\shamp\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
c:\users\shamp\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
c:\users\shamp\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
c:\users\shamp\appdata\local\programs\python\pyt

In [25]:
np.mean(scores),np.std(scores)

(0.79125, 0.04921078529030897)

In [26]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

In [27]:
pipe_svc = make_pipeline(StandardScaler(),SVC(random_state=42))

param_range = [0.0001,0.001,0.01,0.1,1.0,10.0,100.0,1000.0]

param_grid = [{'svc_C':param_range,
               'svc_kernel':['linear']},
              {'svc_C':param_range,
               'svc_kernel':['rbf']}
             ]


In [28]:
gs = GridSearchCV(estimator=pipe_svc,param_grid=param_grid,scoring='accuracy',n_jobs=-1)

gs = gs.fit(X_train,y_train)


c:\users\shamp\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


ValueError: Invalid parameter svc_C for estimator Pipeline(memory=None,
     steps=[('standardscaler', StandardScaler(copy=True, with_mean=True, with_std=True)), ('svc', SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=42,
  shrinking=True, tol=0.001, verbose=False))]). Check the list of available parameters with `estimator.get_params().keys()`.

In [ ]:
print(gs.best_score_)
print(gs.best_params_)